services:
  db:
    container_name: pg-rails
    image: postgres:14.2-alpine3.15
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - "5454:5432"
    networks:
      - backend
  api:
    container_name: api
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    command: puma
    working_dir: /api
    volumes:
      - .:/api
    ports:
      - "3000:3000"
    networks:
      - backend
    depends_on:
      - db
networks:
  backend:
    driver: bridge
volumes:
  db: